void hello_world();
void printf_formatting();
void basic_calculator();
void loops();
void scanf_example1();
void scanf_example2();
void arithmetical_progression();
void sequence_sum();
void salary_calculation();
void simple_pointers_example();
void pointers_grades_example();
void pointers_example_2();
void findMinMax(int num1, int num2, int *pMax, int *pMin);
int palindrome(int arrPalindorme[], int size);
int largestSum(int array1[]);
const char *checkArrayOrder(int array4[], int size);
int milionDollars();
void printPyramid(int rows);
void findOnlySingleElements(int arrayToCheck[], int size);
void printWithoutRepetitions(int arrayToCheck[], int size);
void rotate_array_n(int array7[], int shift, int size);
void rotate_array_right(int array7[], int shift, int size);
void time_to_drive();
void convertToHoursMinutesSeconds();
void convertToSeconds();
void findBiggerNumber();
void reverseNumber();
void hexadecimalToBinary();
void grade();
void calculateDistanceBetweenPoints(float x1, float x2, float y1, float y2);
void findMultipliedElements(int arrayToCheck[], int size);
void elementsSumClosestToZero(int arayToCountClosetozero[], int size);
void arrayElemntsSum(int array[], int size);
void resetArrayToZero(int *ptr, int size);
void countWordsInSentence();
void isPalindorme(char str5[]);
void initializeStructPrint();
void printNextDate();
int findMaxRecursive(int num);