void hello_world();
void printf_formatting();
void basic_calculator();
void loops();
void scanf_example1();
void scanf_example2();
void arithmetical_progression();
void sequence_sum();
void salary_calculation();
